#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TelerikMovieDatabase.Data.MySql;

namespace TelerikMovieDatabase.Data.MySql	
{
	public partial class TelerikMovieDatabaseMySqlContext : OpenAccessContext, ITelerikMovieDatabaseMySqlContextUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public TelerikMovieDatabaseMySqlContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public TelerikMovieDatabaseMySqlContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public TelerikMovieDatabaseMySqlContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public TelerikMovieDatabaseMySqlContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public TelerikMovieDatabaseMySqlContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<GrossReport> GrossReports 
		{
			get
			{
				return this.GetAll<GrossReport>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of TelerikMovieDatabaseMySqlContext.
		/// </summary>
		/// <param name="config">The BackendConfiguration of TelerikMovieDatabaseMySqlContext.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface ITelerikMovieDatabaseMySqlContextUnitOfWork : IUnitOfWork
	{
		IQueryable<GrossReport> GrossReports
		{
			get;
		}
	}
}
#pragma warning restore 1591
