#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace TelerikMovieDatabase.Data.MySql	
{
	public partial class GrossReport
	{
		private int _reportID;
		public virtual int ReportID
		{
			get
			{
				return this._reportID;
			}
			set
			{
				this._reportID = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private decimal _gross;
		public virtual decimal Gross
		{
			get
			{
				return this._gross;
			}
			set
			{
				this._gross = value;
			}
		}
		
	}
}
#pragma warning restore 1591
